version: "3.8"
services:
     nodeserver:
         build:
             context: ./nodejs
         ports:
             - "1234:3000"
     nginx:
         restart: always
         build:
             context: ./nginx
         ports:
             - "80:80"